### ISSUE TITLE
Chris's TODO list

### ISSUE THREAD

**Issue by chrisdickinson** [entropic-dev/entropic#81]
Here's what I'm thinking the priority list is:

- [ ] tests
    - [x] fix linting
- [ ] validation
- [ ] offline work
    - [ ] syncing
        - [ ] create legacy maintainer link to synced packages
    - [ ] revalidation
    - [ ] unify sync and publish
- [ ] EMFILE in storage layer
- [ ] s3 backend
- [ ] cli
    - [ ] bin files
    - [ ] better output on publish
    - [ ] init
    - [x] help functionality (thanks @toddself!)
    - [ ] build
        - [ ] devDependencies
        - [ ] install <foo>
        - [ ] install
        - [ ] stanza bonanza (support the following load-bearing stanzas from package.json in Package.toml & package-versions)
            - [ ] bin stanza
            - [ ] main stanza
- [ ] www
    - [ ] styles?
    - [ ] separate process

**Comment by toddself** [comment]
I've implemented a basic "here are the commands i am aware of" part of help in #100.

For help on specific topics, where should that text get stored?  Part of me thinks that the commands themselves might just export a string that is their help? or perhaps a `.txt` file next to the `.js` file that can be output to the console so node doesn't have to parse all that string stuff?

**Comment by chrisdickinson** [comment]
Ooh, I really like the idea of adding adjacent `help-<command>.txt` files. Keeps it out of the way for tab-complete & out of the file, while still being clear.

**Comment by chrisdickinson** [comment]
Closing this for now because it's intended for a _very specific_ audience (of one!)
